####
POST http://localhost:3000/doctor-api/create-doctor
Content-Type: application/json

{
    "name":"Mahadhyut",
    "designation":"MA, MPhill etc.,",
    "hospital":"Yashoda",
    "location":"Hyderabad",
    "latitude":17.5389868,
    "longitude":78.3959462
}